const ONE_MINUTE_IN_SECONDS = 60;
const ONE_HOUR_IN_SECONDS = 60 * ONE_MINUTE_IN_SECONDS;

const CALENDAR_REFRESH_TIME = 24 * ONE_HOUR_IN_SECONDS;
const CONFIG_REFRESH_TIME = 5 * ONE_MINUTE_IN_SECONDS;
const DEPARTURES_REFRESH_TIME = ONE_MINUTE_IN_SECONDS;

module.exports = {
  ONE_MINUTE_IN_SECONDS,
  ONE_HOUR_IN_SECONDS,
  CALENDAR_REFRESH_TIME,
  CONFIG_REFRESH_TIME,
  DEPARTURES_REFRESH_TIME
};
